# Generated by Django 4.0.4 on 2022-05-26 21:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_formation_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='formation',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
