# Generated by Django 4.0.4 on 2022-06-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_course_content_alter_formation_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-title']},
        ),
        migrations.AlterModelOptions(
            name='formation',
            options={'ordering': ['-title']},
        ),
    ]
